image:
  repository: prestodb/presto
  tag: 0.286
mode: cluster
coordinator:
  replicas: 1
  resources:
    requests:
      memory: "8Gi"
      cpu: "2000m"
    limits:
      memory: "16Gi"
      cpu: "4000m"
worker:
  replicas: 3
  resources:
    requests:
      memory: "8Gi"
      cpu: "2000m"
    limits:
      memory: "16Gi"
      cpu: "4000m"
ingress:
  enabled: true
  host: presto.stage-data.nb-stage.com
  ingressClassName: nginx-internal
catalog:
  hive: |-
    hive.metastore-refresh-interval=1m
    connector.name=hive-hadoop2
    hive.metastore-cache-ttl=20m
    # hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
    hive.non-managed-table-writes-enabled = true
    hive.s3-file-system-type = PRESTO
    hive.hdfs.impersonation.enabled = true
    hive.ranger.rest-endpoint = http://ranger-server.k8s.nb-prod.com/
    hive.ranger.refresh-policy-period = 20s
    hive.security = ranger
    hive.ranger.audit.path = /opt/presto-server/etc/ranger-hive-audit.xml
    hive.ranger.service.basic-auth-password = nb_ranger@2022
    hive.ranger.service.basic-auth-username = admin
    hive.ranger.policy.hive-servicename = hive
    #security.refresh-period=50s
    # hive.metastore.uri = thrift://data.emr.ads.nb.com:9083
    hive.metastore.uri = thrift://data.emr.nb.com:9083
    hive.recursive-directories = true
    hive.parquet.use-column-names=true
  hudi: |-
    connector.name=hudi
    hive.metastore.uri=thrift://data.emr.nb.com:9083
config: |-
  query.max-memory=10GB
  query.max-memory-per-node=1400MB
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::047545107514:role/presto-stage-data