{{- if or (eq .Values.mode "cluster") (eq .Values.mode "ha-cluster") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  node.properties: |-
    node.location={{ .Values.node.location }}
    node.environment={{ .Values.node.environment }}
    node.data-dir={{ .Values.node.dataDir }}
  jvm.config: |-
    {{- if .Values.metrics.enabled }}
    -javaagent:{{ .Values.metrics.javaagent }}={{ .Values.metrics.port }}:{{ .Values.home }}/etc/jmx_exporter.yaml
    {{- end }}
    {{- .Values.worker.jvm | default .Values.jvm | nindent 4 }}
  config.properties: |-
    coordinator=false
    http-server.http.port={{ .Values.service.port }}
    discovery.uri=http://{{ .Release.Name }}-discovery:{{ .Values.service.port }}
    resource-manager-enabled={{ eq .Values.mode "ha-cluster" }}
    {{- .Values.config | nindent 4 }}
  log.properties: |-
    {{- .Values.log | nindent 4 }}
  {{- if .Values.metrics.enabled }}
  jmx_exporter.yaml: |-
    {{- toYaml .Values.metrics.config | nindent 4 }}
  {{- end }}
  ranger-hive-audit.xml: |-
    {{- .Values.ranger_hive_audit_xml | nindent 4 }}
{{- end }}
